import type { EvSpec, PolicyDef, InitiativeDef } from '../data8';
import { opt, S, E } from '../dataKit';

/** Topic: Accounting and statements. Every id starts with "accounting_" (policies and projects) or "e9_accounting_" (events). */
export const policies: PolicyDef[] = [
  { id: 'accounting_close', group: 'finance', name: 'Monthly close deadline', blurb: 'Closing the books means finishing the month\'s records so you know the true profit. Your board expects the numbers by a deadline and may fine you if you are late.', options: [
    opt('Close when it is ready', 'No fixed deadline. Relaxed, but the numbers turn up late and decisions have to wait.', {}),
    opt('Close by working day 10', 'The numbers are due on the tenth working day (a weekday, not a weekend) of the month. Fair, with the odd late month.', { c: 0.997, risk: [4, 1, 'The close ran past the board\'s deadline and you paid a late-close penalty.'] }, 0.2),
    opt('Close by working day 5', 'A hard deadline. Fast numbers and quick decisions, but the finance team is stretched and slips are costly.', { c: 0.994, m: -0.1, risk: [7, 1.5, 'The close missed the board\'s tight deadline and you paid a late-close penalty.'] }, 0.5)] },
  { id: 'accounting_accruals', group: 'finance', name: 'Month-end accruals checklist', blurb: 'An accrual is a cost or a sale you record in the month it really happened, even if the bill or the payment turns up later. Doing it properly keeps your books honest.', options: [
    opt('Record things as they arrive', 'Bills go in when they turn up, so some months look better or worse than they really were.', {}),
    opt('Run a month-end checklist', 'Each month your team lists unbilled work and unpaid bills. The books are cleaner and lenders trust them more.', { od: 1.05, c: 0.998 }, 0.25, 0.2),
    opt('Checklist and a second reviewer', 'A second person signs off every month. The cleanest books you can have, but it slows everything down.', { od: 1.08, c: 0.997, cap: 0.995 }, 0.5, 0.3)] },
  { id: 'accounting_depreciation', group: 'finance', name: 'Depreciation method', blurb: 'Depreciation spreads the price of a machine or a van across the years it is useful. The method you pick changes how much profit you report in each year.', options: [
    opt('Straight-line', 'The same slice every year. Simple, steady and easy to explain.', {}),
    opt('Reducing balance', 'Bigger slices in the early years and smaller ones later. Profit looks lower at first, which trims your tax bill, but lenders get a little cautious.', { od: 0.96 }, -0.2)] },
  { id: 'accounting_stockvalue', group: 'ops', name: 'Inventory valuation', stock: true, blurb: 'How you put a value on the stock on your shelves changes your profit. When prices are rising, valuing stock at the old cheap price makes profit look bigger than it really is.', options: [
    opt('First in, first out', 'Assume the oldest stock sells first. The usual choice, and profit looks higher when prices rise.', {}),
    opt('Average cost', 'Blend every purchase price together. Profit is smoother, which makes planning easier, and it costs a little admin.', { c: 0.997 }, 0.1),
    opt('Prudent write-downs', 'Mark slow stock down early. Profit looks lower on paper, but you spot dead stock sooner, clear it and waste less.', { c: 0.994, d: 0.995 }, 0.2)] },
  { id: 'accounting_revrec', group: 'finance', name: 'Revenue on long contracts', blurb: 'When a job takes months, when do you count the sale? That choice moves your reported profit around and changes when you send the invoice.', options: [
    opt('Count it when finished', 'Simple, but profit arrives in big lumps at the end of each job.', {}),
    opt('Count it as work progresses', 'A little more admin every month. Profits are steadier and lenders like that.', { od: 1.05 }, 0.3),
    opt('Invoice at milestones', 'Bill at agreed stages so cash arrives sooner. Some customers do not like paying before the job is done.', { od: 1.08, d: 0.99 }, 0.15)] },
  { id: 'accounting_variance', group: 'finance', name: 'Budget variance review', blurb: 'A variance is the gap between what you planned to spend or earn and what really happened. Reviewing the gaps shows where money leaks away.', options: [
    opt('No formal budget', 'You run things by feel and look at the bank balance now and then.', {}),
    opt('Quarterly variance review', 'Four times a year, compare plan with reality and chase the biggest gaps.', { c: 0.997 }, 0.15),
    opt('Monthly variance review', 'Every month, sit down with each budget holder and ask why. Costs stay tight, but managers feel watched.', { c: 0.993, m: -0.15 }, 0.35)] },
  { id: 'accounting_mgmtaccounts', group: 'finance', name: 'Management accounts', blurb: 'Statutory accounts are the formal yearly accounts the law makes you file. Management accounts are your own faster, more detailed monthly numbers for running the business.', options: [
    opt('Statutory accounts only', 'Just the legal minimum, once a year. Cheap, but you are driving by looking in the mirror.', {}),
    opt('Monthly management accounts', 'Detailed numbers every month to help you decide things. They take a bookkeeper\'s time.', { c: 0.996, od: 1.03 }, 0.35),
    opt('Management accounts and a bank pack', 'The monthly numbers plus a tidy summary pack for your board and your bank. Pricey but impressive.', { c: 0.994, od: 1.05 }, 0.6, 0.3)] },
  { id: 'accounting_allocation', group: 'finance', name: 'Cost-allocation rules', blurb: 'Overheads are costs that belong to everyone, like rent and the accountant. The rule you use to share them out decides which products look profitable.', options: [
    opt('Split equally', 'Every product carries the same slice of the overheads.', {}),
    opt('Split by sales', 'Quick and cheap. Big sellers carry more cost, so slow products can hide behind them and nobody notices.', { c: 1.004 }, -0.1),
    opt('Activity-based costing', 'Charge each product for the work it really causes. It takes effort, but it shows the true winners and losers.', { c: 0.994 }, 0.4, 0.3)] },
];

export const events: EvSpec[] = [
  { id: 'e9_accounting_bankrec', title: 'The bank check finds a missing payment', icon: 'chart', good: true, per: 1.2, cd: 14, story: 'Your monthly bank reconciliation (matching your own records to the bank statement, line by line) has turned up a payment that never reached your books. Either a customer paid and nobody logged it, or they never paid at all.', choices: [
    S('chase', 'Chase the missing money', 'Takes a few emails, and you will probably get paid.', 'A polite reminder and a copy of the payment slip later, the money landed in your account.', { income: 0.1 }),
    S('writeoff', 'Write it off as a one-off', 'Free and fast, but you lose the money.', 'You wrote it off and moved on. The books are tidy, though the cash is gone.'),
    S('system', 'Fix the process that missed it', 'Pay for tighter weekly checks so it cannot happen again.', 'You added a weekly matching routine. Fewer surprises are coming.', { k: 0.015, eff: { c: E(0.995, 8) } })] },
  { id: 'e9_accounting_baddebt', title: 'Doubtful debts: how much to set aside?', icon: 'shield', good: false, per: 1, cd: 12, min: 10, story: 'Some customers have not paid for months. A provision is money you set aside, on paper, for debts you probably will not collect. You have to estimate how much, and it changes the profit you report.', choices: [
    S('prudent', 'Provide generously', 'Lower reported profit now, fewer shocks later.', 'You set aside a generous amount. Profit looked lower, but when one customer failed it did not hurt, and the bank noticed your caution.', { k: 0.02, eff: { rep: 1 } }),
    S('light', 'Provide only a small amount', 'Profit looks better, but a bigger loss could land later.', '', { k: 0.005, gamble: { p: 0.5, good: {}, bad: { c: E(1.02, 4), rep: -1 }, goodText: 'Customers paid up and the small provision was enough.', badText: 'Two customers failed and the loss hit with no cushion to soften it.' } }),
    S('none', 'Provide nothing and hope', 'Looks best on paper and is the riskiest.', '', { gamble: { p: 0.35, good: {}, bad: { c: E(1.03, 6), rep: -2 }, goodText: 'Everyone paid in the end. You were lucky.', badText: 'A big customer failed, and the surprise loss shook the bank\'s trust in your numbers.' } })] },
  { id: 'e9_accounting_cashflowtalk', title: 'Investors want a cash-flow walk-through', icon: 'chart', good: true, per: 1, cd: 18, min: 12, story: 'A possible investor says profit is nice, but cash is what pays the bills. They want you to walk them through your cash-flow statement, the report that shows where cash came from and where it went, split into running the business, investing and financing.', choices: [
    S('present', 'Prepare a proper walk-through', 'Takes preparation, and impresses careful people.', '', { k: 0.01, gamble: { p: 0.8, good: { rep: 1, brand: 1.01 }, bad: {}, goodText: 'You explained every line clearly and they were impressed.', badText: 'They still had questions you could not answer, and the meeting fizzled out.' } }),
    S('sheet', 'Send the statement with a short note', 'Quick and safe, and not much of an impression.', 'They read it, said thank you and nothing more came of it.'),
    S('bluster', 'Talk about profit and growth only', 'Charming, and risky if they spot the gap.', '', { gamble: { p: 0.4, good: { brand: 1.01 }, bad: { rep: -2 }, goodText: 'Your confidence charmed them.', badText: 'They noticed you skipped the cash, and their trust dropped.' } })] },
  { id: 'e9_accounting_restate', title: 'The auditors find an error', icon: 'key', good: false, per: 0.9, cd: 24, min: 12, story: 'Your auditors, who check your accounts independently, have found a mistake in last year\'s figures: a sale was counted a year too early. To fix it you must restate, which means publishing the corrected numbers and explaining what changed.', choices: [
    S('open', 'Restate openly and explain', 'Honest, a little painful, and usually forgiven.', '', { k: 0.02, gamble: { p: 0.8, good: { rep: 1 }, bad: { rep: -1 }, goodText: 'People respected your honesty, and the story faded fast.', badText: 'A few lenders were nervous about the correction for a while.' } }),
    S('quiet', 'Fix it in this year\'s numbers', 'Cheaper, but the auditors may refuse.', '', { gamble: { p: 0.4, good: {}, bad: { rep: -3, c: E(1.02, 4) }, goodText: 'The auditors accepted a small adjustment and let it go.', badText: 'The auditors refused, called it hiding an error, and word got out.' } }),
    S('argue', 'Challenge the auditors', 'They may agree with you, and they may not.', '', { k: 0.01, gamble: { p: 0.35, good: { rep: 1 }, bad: { rep: -2, morale: -1 }, goodText: 'They checked again and agreed that your treatment was fine.', badText: 'They stood firm and you looked stubborn.' } })] },
  { id: 'e9_accounting_relatedparty', title: 'A relative\'s firm did some work for you', icon: 'key', good: false, per: 1, cd: 24, story: 'A company owned by a relative of yours was paid for some work. That is a related-party transaction, a deal with someone close to the business, and it must be disclosed in the accounts so readers can check the price was fair.', choices: [
    S('disclose', 'Disclose it in the notes', 'Honest and cheap to do, and it earns some trust.', 'You listed the deal in the notes to the accounts. Nobody raised an eyebrow, and the auditors were pleased.', { k: 0.003, eff: { rep: 1 } }),
    S('retender', 'Disclose it and put the work out to tender', 'Costs effort, and you might find a cheaper supplier.', 'Three quotes came back and one was cheaper. You switched, and the family dinner was a little awkward.', { k: 0.01, eff: { c: E(0.99, 6), morale: -1 } }),
    S('hide', 'Leave it out of the accounts', 'Free, and a serious problem if anyone notices.', '', { gamble: { p: 0.5, good: {}, bad: { rep: -3, d: E(0.98, 4) }, goodText: 'Nobody noticed this year.', badText: 'The auditors spotted it, and trust took a real hit.' } })] },
  { id: 'e9_accounting_contingent', title: 'A customer threatens to sue', icon: 'shield', good: false, per: 1, cd: 18, min: 10, story: 'A customer says your product caused them losses and may take you to court. A contingent liability is a possible debt that depends on a future event, like a court ruling. Accounting rules say you must tell readers of your accounts about it.', choices: [
    S('note', 'Note it in the accounts and fight', 'Honest, and it could go either way.', '', { k: 0.015, gamble: { p: 0.65, good: { rep: 1 }, bad: { rep: -2, c: E(1.02, 3) }, goodText: 'The claim was dropped, and your open notes looked sensible.', badText: 'You lost in court and the costs bit.' } }),
    S('settle', 'Set money aside and settle quickly', 'Costs more now and ends the worry.', 'You settled before it got ugly, and the note in the accounts was removed.', { k: 0.04 }),
    S('silent', 'Say nothing in the accounts', 'Free and risky if the claim goes ahead.', '', { gamble: { p: 0.4, good: {}, bad: { rep: -4 }, goodText: 'The customer never followed through.', badText: 'The claim went ahead, and the accounts were found to be misleading.' } })] },
  { id: 'e9_accounting_fxreval', title: 'Month-end currency revaluation stings', icon: 'globe', good: false, per: 1, cd: 12, min: 10, story: 'A foreign customer owes you money in their own currency. At month end the accountants revalue the debt into pounds, and the exchange rate has moved against you, so the books show a loss even though you have not yet lost any cash.', choices: [
    S('forward', 'Lock the rate with a forward contract', 'Costs a fee and removes the surprises.', 'You agreed a fixed rate for the coming months, so the swings stopped bothering you.', { k: 0.01 }),
    S('pounds', 'Ask customers to pay in pounds', 'No more swings for you, but customers may grumble.', 'Most customers agreed. A couple found it awkward and ordered a little less.', { eff: { d: E(0.985, 6) } }),
    S('wait', 'Leave it and see where the rate goes', 'Free, and anything could happen.', '', { gamble: { p: 0.5, good: { d: E(1.01, 4) }, bad: { c: E(1.015, 4) }, goodText: 'The rate bounced back and the loss vanished.', badText: 'The rate kept sliding, and the paper loss became a real one.' } })] },
  { id: 'e9_accounting_leases', title: 'Your leases move onto the balance sheet', icon: 'gear', good: false, per: 0.9, cd: 30, min: 12, story: 'A rule change says rented premises and equipment must now show on the balance sheet as a right-of-use asset (what you are allowed to use) matched by a lease liability (what you still owe). You look more indebted than before, though nothing about the leases has changed.', choices: [
    S('adopt', 'Adopt the new rules properly', 'Costs some accountant time, and the books are right.', 'You rebuilt your lease schedule. The debt figure looks bigger, but it is an honest one.', { k: 0.015 }),
    S('shorten', 'Renegotiate to short leases', 'Leases under a year can stay off the balance sheet, though landlords charge for flexibility.', 'Several landlords agreed to short terms, and charged a bit more for the freedom.', { eff: { c: E(1.01, 12) } }),
    S('brief', 'Brief your bank on the change', 'A quick chat to stop them panicking.', '', { k: 0.005, gamble: { p: 0.8, good: { rep: 1 }, bad: { c: E(1.01, 4) }, goodText: 'The bank understood it was just a change in how leases are shown.', badText: 'The bank tightened its terms for a few months anyway.' } })] },
  { id: 'e9_accounting_impairment', title: 'The impairment test gives a nasty surprise', icon: 'diamond', good: false, per: 0.9, cd: 24, min: 12, story: 'Each year you must test whether anything on your balance sheet is now worth less than you paid for it. This year the test says a past purchase is worth far less than the books say. Writing down its value is called an impairment, and it cuts your reported profit.', choices: [
    S('writedown', 'Write it down in full', 'Painful for profit, and honest.', 'You took the whole hit in one go. It stung, but the books are clean and the auditors approved.', { eff: { rep: 1, morale: -2 } }),
    S('partial', 'Write down part and hope it recovers', 'Smaller hit now, a bigger one if you are wrong.', '', { gamble: { p: 0.5, good: {}, bad: { rep: -2, c: E(1.01, 4) }, goodText: 'The asset recovered, and the partial write-down was enough.', badText: 'It lost more value and you had to write down again, which looked sloppy.' } }),
    S('second', 'Pay for a second valuation', 'Costs money, and the answer may be kinder.', '', { k: 0.02, gamble: { p: 0.6, good: { rep: 1 }, bad: { rep: -1 }, goodText: 'The second valuer put the asset higher, and the auditors accepted it.', badText: 'The second valuer agreed with the first, and you paid for bad news twice.' } })] },
  { id: 'e9_accounting_budgetseason', title: 'Budget season: every team wants more', icon: 'chart', good: true, per: 1.2, cd: 12, min: 12, gate: 'team', story: 'It is budget season. Every team has put in a bid for next year\'s money, and together they ask for far more than you can afford. You must decide how to share out the pot.', choices: [
    S('squeeze', 'Cut every bid by a quarter', 'Fair on paper and annoying in practice.', 'Everyone grumbled equally. Costs held, and a few good ideas were starved.', { eff: { morale: -2, c: E(0.995, 12) } }),
    S('priorities', 'Fund the best business cases', 'Some teams win, and some lose out.', '', { k: 0.01, gamble: { p: 0.7, good: { quality: 1, c: E(0.99, 8) }, bad: { morale: -2 }, goodText: 'Money went where it earned most, and the best teams delivered.', badText: 'The teams that lost out sulked all spring.' } }),
    S('rubber', 'Approve every bid', 'Everyone is happy until the money runs short.', 'Everyone cheered, and spending crept up through the year.', { eff: { morale: 3, c: E(1.015, 8) } })] },
  { id: 'e9_accounting_bookkeeper', title: 'The bookkeeper is worn out', icon: 'coffee', good: false, per: 1.2, cd: 10, story: 'Your bookkeeper, who keeps the day-to-day records, is working flat out and has started making slips: a bill entered twice, a payment on the wrong date. Tired people make mistakes, and mistakes in the books cost real money.', choices: [
    S('help', 'Hire some part-time help', 'Costs wages and clears the backlog.', 'A second pair of hands cleared the pile, and the slips stopped.', { k: 0.02, acct: 'wages', eff: { morale: 1 } }),
    S('software', 'Buy software with automatic checks', 'A fee now and fewer slips later.', 'The software flags duplicates and odd dates. Errors dropped, and it keeps on helping.', { k: 0.015, eff: { c: E(0.996, 12) } }),
    S('careful', 'Ask them to be more careful', 'Free, and it does not fix the cause.', '', { gamble: { p: 0.4, good: {}, bad: { c: E(1.02, 3), morale: -2 }, goodText: 'They double-checked everything and the slips stopped for a while.', badText: 'A bigger mistake slipped through, and the bookkeeper is close to quitting.' } })] },
];

export const projects: InitiativeDef[] = [
  { id: 'accounting_chartaccounts', name: 'Customise your chart of accounts', blurb: 'The chart of accounts is the list of headings your money is filed under. Tailor it to your business so your reports show what you really need to see.', k: 0.4, months: 3, success: 85,
    win: { eff: { c: 0.996 }, text: 'Your reports now split costs the way your business really works, and waste is much easier to spot.' },
    lose: { now: { morale: -1 }, text: 'The new headings confused the team and had to be rolled back.' } },
  { id: 'accounting_segments', name: 'Segment reporting by product line', blurb: 'Report the profit of each product line separately, so you can see which ones really earn their keep and which ones ride on the others.', k: 0.6, months: 4, success: 75,
    win: { eff: { c: 0.993, d: 1.003 }, monthly: 0.1, text: 'You found one line that lost money and fixed it, and your best line got more attention.' },
    lose: { now: { c: E(1.01, 3) }, text: 'The shared costs were argued over for weeks and the split never felt fair.' } },
  { id: 'accounting_dashboard', name: 'Ratio dashboard with traffic lights', blurb: 'A ratio compares two numbers, such as debt against profit, to show how healthy you are. Build a one-page dashboard that turns each ratio red, amber or green.', k: 0.5, months: 3, success: 80,
    win: { eff: { c: 0.996, od: 1.04 }, monthly: 0.1, text: 'You spot trouble early, and the bank loves seeing your numbers laid out so plainly.' },
    lose: { now: { morale: -1 }, text: 'Nobody agreed what green should mean, and the dashboard was quietly dropped.' } },
  { id: 'accounting_assetregister', name: 'Fixed-asset register tidy-up', blurb: 'Walk round and match every asset in your books to a real thing. Sometimes you find ghost assets: items you still list, insure and service but no longer own.', k: 0.3, months: 2, success: 85,
    win: { monthly: -0.2, text: 'You found several ghost assets, cancelled the insurance on them and stopped paying to service them.' },
    lose: { now: { morale: -1 }, text: 'It took a whole weekend and everything matched. The count was dull and found nothing.' } },
  { id: 'accounting_rollingforecast', name: 'Rolling twelve-month forecast', blurb: 'Instead of one fixed yearly budget, update a forecast every month so it always looks a full year ahead. It keeps you ready for what is coming.', k: 0.7, months: 4, success: 75,
    win: { eff: { c: 0.994, od: 1.05 }, monthly: 0.15, text: 'You see problems months ahead, and your bank trusts a boss who plans like this.' },
    lose: { now: { morale: -1 }, text: 'The forecast changed so often that nobody believed it, and the team dropped it.' } },
];
